[[news]]
date = "2025-09"
content = "Our paper about client sampling for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2025-06"
content = "I received the master degree from Chongqing University. Happy!!!"

[[news]]
date = "2025-01"
content = "Our paper about client selection and bandwidth allocation for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2024-01"
content = "Our paper about client sampling for federated learning is accepted by IEEE ICC 2024."

