[[news]]
date = "2025-09"
content = "Our paper about client sampling for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2025-06"
content = "I received the master degree from Chongqing University. Happy!!!"

[[news]]
date = "2025-02"
content = "I was honored to be asked to be a reviewer for International ACM SIGIR Conference on Research and Development in Information Retrieval (SIGIR)."

[[news]]
date = "2025-01"
content = "Our paper about client selection and bandwidth allocation for federated learning has been accepted by IEEE TMC."

[[news]]
date = "2024-08"
content = "I was honored to be asked to be a reviewer for IEEE Transactions on Cognitive Communications and Networking (IEEE TCCN)."

[[news]]
date = "2024-01"
content = "Our paper about client sampling for federated learning is accepted by IEEE ICC 2024."

[[news]]
date = "2023-10"
content = "Our paper about client sampling for federated learning has been submitted to the IEEE ICC for review."
